#!/bin/bash

printf '<100°F: \e[1;44m \e[0m <125°F: \e[1;42m \e[0m <150°F: \e[1;43m \e[0m <190°F: \e[1;41m \e[0m\n'

while read -r line; do
    if [[ $line =~ ^[a-z]*- ]]; then
        device=$line
        printf '\n%s\n' "$device"
    elif [[ $line =~ : ]]; then
        sensor="${line%%:*}"
        temp=${line#*+}; temp="${temp%%.*}"

        if (( temp < 100 )); then
            color=4
        elif (( temp < 125 )); then
            color=2
        elif (( temp < 150 )); then
            color=3
        elif (( temp < 190 )); then
            color=1
        else
            color=1
            printf '%s\n' 'Temperature at critical level'
        fi

        printf '%s: \e[3%dm%d\e[m°F\n' "$sensor" "$color" "$temp"
    fi
done < <(sensors -fA) 
